site_name: Knative
site_url: https://knative.dev/docs
site_description: Knative Documentation
extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/knative/docs
edit_uri: edit/main/docs

nav:
    - Home: index.md
    - Getting Started:
        - Before you begin: getting-started/getting-started.md
        - Serverless:
          - First Knative Service: getting-started/first-service.md
          - Scaling to Zero: getting-started/first-autoscale.md
          - Traffic Splitting: getting-started/first-traffic-split.md
        - Event-Driven Applications:
          - Introducing Knative Eventing: getting-started/getting-started-eventing.md
          - Sources, Brokers, Triggers, Sinks: getting-started/first-broker.md
          - Introducing the CloudEvents Player: getting-started/first-source.md
          - Creating your first Trigger: getting-started/first-trigger.md
        - What's Next?: getting-started/next-steps.md
    - Installing Knative:
        - Installing using YAML:
          - Prerequisites: install/prerequisites.md
          - Install Serving with YAML: install/install-serving-with-yaml.md
          - Install Eventing with YAML: install/install-eventing-with-yaml.md
          - Install optional extensions: install/install-extensions.md
          - Installation Files: install/installation-files.md
        - Installing with the Operator: install/knative-with-operators.md
        - Using a Knative-based Offering: install/knative-offerings.md
    - Serving Component:
        - Overview: serving/README.md
        - Developer Topics:
          - Creating Knative Services: serving/services/creating-services.md
          - Creating and Using Sub-Routes: serving/using-subroutes.md
          - Using a Private Registry: serving/deploying/private-registry.md
          - Debugging Issues with your Application: serving/debugging-application-issues.md
          - Gradually Rolling out Revisions: serving/rolling-out-latest-revision.md
          - Custom Domains:
            - Setting up a Custom Domain: serving/using-a-custom-domain.md
            - Setting up a Custom Domain per Service: serving/using-a-custom-domain-per-service.md
            - Creating Domain Mappings: serving/creating-domain-mappings.md
          - Using Knative Load Balancing:
            - Overview: serving/load-balancing/index.md
            - Target Burst Capacity: serving/load-balancing/target-burst-capacity.md
        - Administrator Topics:
          - Configuring the Knative Deployment: serving/services/deployment.md
          - Accessing Request Traces: serving/accessing-traces.md
          - Knative Kubernetes Components: serving/knative-kubernetes-services.md
          - Enabling tag to digest resolution: serving/tag-resolution.md
          - Configuing Cluster-Local Services: serving/cluster-local-route.md
          - Configuring high-availability components: serving/config-ha.md
          - Feature Flags: serving/feature-flags.md
          - Exclude namespaces from the Knative webhook: serving/webhook-customizations.md
          - Configuring HTTPS Connections: serving/using-a-tls-cert.md
          - Setting up Cert-Manager:
            - Installing cert-manager for TLS Certificates: serving/installing-cert-manager.md
            - Configuring HTTPS with cert-manager and Google Cloud DNS: serving//using-cert-manager-on-gcp.md
            - Enabling automatic TLS certificate provisioning: serving/using-auto-tls.md
        - Autoscaling:
          - Overview: serving/autoscaling/README.md
          - Concepts: serving/autoscaling/autoscaling-concepts.md
          - Metrics: serving/autoscaling/autoscaling-metrics.md
          - Targets: serving/autoscaling/autoscaling-targets.md
          - Configuring Scale-to-zero: serving/autoscaling/scale-to-zero.md
          - Configuring Concurrency: serving/autoscaling/concurrency.md
          - Configuring Scale Bounds: serving/autoscaling/scale-bounds.md
          - Configuring RPS Target: serving/autoscaling/rps-target.md
          - KPA-Specific Configuration: serving/autoscaling/kpa-specific.md
          - Autoscaling Sample App: serving/autoscaling/autoscale-go/README.md
        - GKE-Specific Customization:
          - Assigning Static IPs in GKE: serving/gke-assigning-static-ip-address.md
          - Using ExternalDNS on Google Cloud Platform to automate DNS setup: serving/using-external-dns-on-gcp.md
        - Istio-Specific Configuration:
          - Setting up custom ingress gateway: serving/setting-up-custom-ingress-gateway.md
          - Enabling requests to Knative services when additional authorization policies are enabled: serving/istio-authorization.md
        - Samples:
          - Overview: serving/samples/README.md
          - Hello World:
            - Hello World Go: serving/samples/hello-world/helloworld-go/index.md
          - Rest API: serving/samples/rest-api-go/README.md
          - Cloud Events:
            - NodeJS: serving/samples/cloudevents/cloudevents-nodejs/README.md
            - Java (Vert.x): serving/samples/cloudevents/cloudevents-vertx/README.md
            - Rust: serving/samples/cloudevents/cloudevents-rust/index.md
          - Blue Green Deployment: serving/samples/blue-green-deployment.md
    - Eventing Component:
      - Overview: eventing/README.md
      - Getting started: eventing/getting-started.md
      - Event sources:
        - Overview: eventing/sources/README.md
        - API server source:
          - Overview: eventing/sources/apiserversource/README.md
          - Getting started: eventing/sources/apiserversource/getting-started/README.md
        - ContainerSource: eventing/sources/containersource.md
        - PingSource: eventing/sources/ping-source/index.md
        - Sink binding: eventing/sources/sinkbinding.md
        - Camel source: eventing/sources/apache-camel-source/index.md
      - Creating an event source:
        - Overview: eventing/sources/creating-event-sources/README.md
        - Writing an event source using Javascript: eventing/sources/creating-event-sources/writing-event-source-easy-way/README.md
        - Using the sample event source:
          - Overview: eventing/sources/creating-event-sources/writing-event-source/README.md
          - Design of an Event Source: eventing/sources/creating-event-sources/writing-event-source/01-theory.md
          - Lifecycle and Types: eventing/sources/creating-event-sources/writing-event-source/02-lifecycle-and-types.md
          - Controller Implemetation: eventing/sources/creating-event-sources/writing-event-source/03-controller.md
          - Reconciler Implementation: eventing/sources/creating-event-sources/writing-event-source/04-reconciler.md
          - Receive Adapter Implementation: eventing/sources/creating-event-sources/writing-event-source/05-receive-adapter.md
          - Publishing to your cluster: eventing/sources/creating-event-sources/writing-event-source/06-yaml.md
          - Moving to knative-sandbox: eventing/sources/creating-event-sources/writing-event-source/07-knative-sandbox.md
      - Event registry: eventing/event-registry.md
      - Flows:
        - Overview: eventing/flows/README.md
        - Parallel: eventing/flows/parallel.md
        - Sequence:
          - Overview: eventing/flows/sequence/README.md
          - Displaying sequence output: eventing/flows/sequence/sequence-reply-to-event-display/index.md
          - Using Sequences in series: eventing/flows/sequence/sequence-reply-to-sequence/index.md
          - Create additional events: eventing/flows/sequence/sequence-terminal/index.md
          - Using with Broker and Trigger: eventing/flows/sequence/sequence-with-broker-trigger/index.md
      - Channels:
        - Overview: eventing/channels/README.md
        - Channel types and defaults: eventing/channels/channel-types-defaults.md
        - Creating a channel using cluster or namespace defaults: eventing/channels/create-default-channel.md
        - Available Channels: eventing/channels/channels-crds.md
        - Subscriptions: eventing/channels/subscriptions.md
      - Sugar Controller: eventing/sugar/README.md
      - Event delivery: eventing/event-delivery.md
      - Brokers:
        - Overview: eventing/broker/README.md
        - Creating a broker: eventing/broker/create-mtbroker.md
        - Triggers: eventing/broker/triggers/README.md
        - Event delivery: eventing/broker/broker-event-delivery.md
        - Broker configuration example: eventing/broker/example-mtbroker.md
        - ConfigMaps: eventing/broker/configmaps/README.md
        - Apache Kafka Broker:
          - Overview: eventing/broker/kafka-broker/README.md
          - Kafka Channel ConfigMap: eventing/broker/kafka-broker/kafka-configmap.md
      - Sink:
        - Overview: eventing/sink/README.md
        - Apache Kafka Sink: eventing/sink/kafka-sink.md
      - Debugging: eventing/debugging/index.md
      - Accessing CloudEvent traces: eventing/accessing-traces.md
      - Metrics API: eventing/metrics.md
      - Code samples:
        - Overview: eventing/samples/README.md
        - Container source: eventing/samples/container-source/index.md
        - Hello World:
          - Overview: eventing/samples/helloworld/README.md
          - GO: eventing/samples/helloworld/helloworld-go/README.md
          - Python: eventing/samples/helloworld/helloworld-python/README.md
        - Apache Kafka:
          - Overview: eventing/samples/kafka/README.md
          - Binding Example: eventing/samples/kafka/binding/index.md
          - Channel Example: eventing/samples/kafka/channel/index.md
          - Source Example: eventing/samples/kafka/source/index.md
        - Parallel:
          - Overview: eventing/samples/parallel/README.md
          - Multiple Cases: eventing/samples/parallel/multiple-branches/README.md
          - Mutual Exclusivity: eventing/samples/parallel/mutual-exclusivity/README.md
        - CloudAuditLogsSource: eventing/samples/cloud-audit-logs-source/index.md
        - CloudPubSubSource: eventing/samples/cloud-pubsub-source/index.md
        - CloudSchedulerSource: eventing/samples/cloud-scheduler-source/index.md
        - CloudStorageSource: eventing/samples/cloud-storage-source/index.md
        - GitHub source: eventing/samples/github-source/index.md
        - GitLab source: eventing/samples/gitlab-source/index.md
        - IoT core: eventing/samples/iot-core/index.md
    - Reference:
      - Serving: reference/api/serving.md
      - Eventing: reference/api/eventing/eventing.md
    - Client:
        - CLI tools: client/index.md
        - Install kn: client/install-kn.md
    - Community: todo

theme:
  name: material
  logo: images/logo/rgb/knative-logo-rgb.png
  favicon: images/knative-sm.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

plugins:
  - search
  - macros:
      module_name: hack/macros
  - exclude:
      glob:
        # Exclude files that contain hugo specific shortcodes
        # (either the include shortcode or not-converted-yet tabs).
        - smoketest.md
        - "*/serving-api.md" # shortcode to serving.md
        - "*/_index.md" # pretty much all shortcodes
        - "*/traffic-splitting/index.md" # shortcode to README
        - "*/secrets-go/index.md" # shortcode to README
        - "*/tag-header-based-routing/index.md" # shortcode to README
        - "*/knative-routing-go/index.md" # shortcode to README
        - "*/helloworld-scala/index.md" # shortcode to README
        - "*/helloworld-python/index.md" # shortcode to README
        - "*/helloworld-php/index.md" # shortcode to README
        - "*/helloworld-nodejs/index.md" # shortcode to README
        - "*/helloworld-csharp/index.md" # shortcode to README
        - "*/helloworld-kotlin/index.md" # shortcode to README
        - "*/cloudevents-dotnet/index.md" # shortcode to README
        - "*/grpc-ping-go/index.md" # shortcode to README
        - "*/gitwebhook-go/index.md" # shortcode to README
        - "*/multi-container/index.md" # shortcode to README

markdown_extensions:
  # - mdx_include:
  #     base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true


copyright: "Copyright © 2021 The Knative Authors"

extra:
  branch: v0.23.0 # Branch to use for examples
  # version for download links, empty or "dev" to use googlestorage nightlies.
  # version: v0.23.0
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KnativeProject
    - icon: fontawesome/brands/github
      link: https://github.com/knative/community
      name: Knative Community on Github
    - icon: fontawesome/brands/slack
      link: https://slack.knative.dev
      name: Slack
  version:
    provider: mike
