site_name: Knative
site_url: https://knative.dev/docs
site_description: Knative Documentation
extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/knative/docs
edit_uri: edit/main/docs

nav:
    - Home: index.md
    - Installing Knative:
      - Overview: install/index.md
      - Prerequisites: install/prerequisites.md
      - Install Serving using YAML: install/install-serving-with-yaml.md
      - Install Eventing using YAML: install/install-eventing-with-yaml.md
      - Install optional extensions: install/install-extensions.md
      - Knative Operator installation: install/knative-with-operators.md
      - Installing Istio for Knative: install/installing-istio.md
      - Checking your install version: install/check-install-version.md
      - Configuring the Serving Operator Custom Resource: install/operator/configuring-serving-cr.md
      - Installation files: install/installation-files.md
      - Collecting logs: install/collecting-logs/README.md
      - Collecting metrics: install/collecting-metrics/index.md
      - Configuring the Eventing Operator custom resource: install/operator/configuring-eventing-cr.md
    - Serving Component:
      - Overview: serving/README.md
      - Getting started: serving/getting-started-knative-app.md
      - Knative Kubernetes Services: serving/knative-kubernetes-services.md
      - Deploying from private registries: serving/deploying/private-registry.md
      - Services:
        - Overview: serving/services/_index.md
        - Deployment Configuration: serving/services/deployment.md
        - Creating Knative services: serving/services/creating-services.md
      - Accessing request traces: serving/accessing-traces.md
      - Autoscaling:
        - Overview: serving/autoscaling/README.md
        - Autoscaling concepts: serving/autoscaling/autoscaling-concepts.md
        - Metrics: serving/autoscaling/autoscaling-metrics.md
        - Targets: serving/autoscaling/autoscaling-targets.md
        - Autoscaling: serving/autoscaling/_index.md
        - Configuring scale to zero: serving/autoscaling/scale-to-zero.md
        - Configuring concurrency: serving/autoscaling/concurrency.md
        - Configuring the requests per second (RPS) target: serving/autoscaling/rps-target.md
        - Configuring scale bounds: serving/autoscaling/scale-bounds.md
        - Additional autoscaling configuration for Knative Pod Autoscaler: serving/autoscaling/kpa-specific.md
        - Autoscale Sample App - Go: serving/autoscaling/autoscale-go/README.md
      - Load Balancing:
        - Overview: serving/load-balancing/index.md
        - Configuring target burst capacity: serving/load-balancing/target-burst-capacity.md
      - Configuring cluster-local services: serving/cluster-local-route.md
      - Gradually rolling out latest Revisions: serving/rolling-out-latest-revision.md
      - Creating and using Subroutes: serving/using-subroutes.md
      - Debugging issues with your application: serving/debugging-application-issues.md
      - Enabling requests to Knative services when additional authorization policies are enabled: serving/istio-authorization.md
      - Assigning static IPs - GKE: serving/gke-assigning-static-ip-address.md
      - Configuring high-availability components: serving/config-ha.md
      - Feature/Extension Flags: serving/feature-flags.md
      - Configuring the ingress gateway: serving/setting-up-custom-ingress-gateway.md
      - Setting up a custom domain: serving/using-a-custom-domain.md
      - Configuring HTTPS connections: serving/using-a-tls-cert.md
      - Installing cert-manager: serving/installing-cert-manager.md
      - Configuring HTTPS with Cloud DNS: serving/using-cert-manager-on-gcp.md
      - Creating Domain Mappings (Alpha): serving/creating-domain-mappings.md
      - Enabling auto TLS certs: serving/using-auto-tls.md
      - Using ExternalDNS on Google Cloud Platform to automate DNS setup: serving/using-external-dns-on-gcp.md
      - Exclude namespaces from the Knative webhook: serving/webhook-customizations.md
      - Tag resolution: serving/tag-resolution.md
      - Code samples:
        - Overview: serving/samples/README.md
        - Routing and managing traffic: serving/samples/blue-green-deployment.md
        - Cloud Events apps:
          - .NET: serving/samples/cloudevents/cloudevents-dotnet/README.md
          - Go: serving/samples/cloudevents/cloudevents-go/index.md
          - Node.js: serving/samples/cloudevents/cloudevents-nodejs/README.md
          - Rust: serving/samples/cloudevents/cloudevents-rust/index.md
          - Java and Spring: serving/samples/cloudevents/cloudevents-spring/README.md
          - Java and Vert.x: serving/samples/cloudevents/cloudevents-vertx/README.md
        - GitHub Webhook - Go: serving/samples/gitwebhook-go/README.md
        - gRPC Server - Go: serving/samples/grpc-ping-go/README.md
        - Hello world apps:
          - .NET: serving/samples/hello-world/helloworld-csharp/README.md
          - Go: serving/samples/hello-world/helloworld-go/index.md
          - Java (Spark): serving/samples/hello-world/helloworld-java-spark/index.md
          - Java (Spring): serving/samples/hello-world/helloworld-java-spring/README.md
          - Kotlin: serving/samples/hello-world/helloworld-kotlin/README.md
          - Node.js: serving/samples/hello-world/helloworld-nodejs/README.md
          - PHP: serving/samples/hello-world/helloworld-php/index.md
          - Python: serving/samples/hello-world/helloworld-python/README.md
          - Ruby: serving/samples/hello-world/helloworld-ruby/index.md
          - Scala: serving/samples/hello-world/helloworld-scala/index.md
          - Shell: serving/samples/hello-world/helloworld-shell/index.md
        - Routing services - Go: serving/samples/knative-routing-go/README.md
        - multi-container samples: serving/samples/multi-container/README.md
        - RESTful service - Go: serving/samples/rest-api-go/README.md
        - Secrets - Go: serving/samples/secrets-go/README.md
        - Tag Header Based Routing: serving/samples/tag-header-based-routing/README.md
        - Traffic splitting: serving/samples/traffic-splitting/README.md
    - Eventing Component:
      - Overview: eventing/index.md
      - Brokers:
        - Overview: eventing/broker/README.md
        - Default Broker ConfigMap: eventing/broker/config-br-defaults.md
        - Apache Kafka Broker: eventing/broker/kafka-broker.md
        - Kafka Channel ConfigMap: eventing/broker/kafka-configmap.md
        - Alternate Brokers: eventing/broker/alternate/README.md
      - Channels:
        - Overview: eventing/channels/index.md
        - Channel types and defaults: eventing/channels/channel-types-defaults.md
        - Creating a channel using cluster or namespace defaults: eventing/channels/create-default-channel.md
        - Available Channels: eventing/channels/channels-crds.md
        - Subscriptions: eventing/channels/subscriptions.md
      - Flows:
        - Overview: eventing/flows/README.md
        - Parallel: eventing/flows/parallel.md
        - Sequence: eventing/flows/sequence.md
      - Sinks:
        - Overview: eventing/sink/README.md
        - Apache Kafka Sink: eventing/sink/kafka-sink.md
      - Event sources:
        - Overview: eventing/sources/README.md
        - Getting started: eventing/getting-started.md
        - APIServerSource: eventing/sources/apiserversource.md
        - ContainerSource: eventing/sources/containersource.md
        - PingSource: eventing/sources/pingsource.md
        - Sink binding: eventing/sources/sinkbinding.md
        - Camel source: eventing/sources/apache-camel-source/index.md
        - Creating an event source:
          - Overview: eventing/sources/creating-event-sources/README.md
          - Writing an event source using Javascript: eventing/sources/creating-event-sources/writing-event-source-easy-way/_index.md
          - Using the sample event source:
            - Overview: eventing/sources/creating-event-sources/writing-event-source/_index.md
            - Design of an Event Source: eventing/sources/creating-event-sources/writing-event-source/01-theory.md
            - Lifecycle and Types: eventing/sources/creating-event-sources/writing-event-source/02-lifecycle-and-types.md
            - Controller Implemetation: eventing/sources/creating-event-sources/writing-event-source/03-controller.md
            - Reconciler Implementation: eventing/sources/creating-event-sources/writing-event-source/04-reconciler.md
            - Receive Adapter Implementation: eventing/sources/creating-event-sources/writing-event-source/05-receive-adapter.md
            - Publishing to your cluster: eventing/sources/creating-event-sources/writing-event-source/06-yaml.md
            - Moving to knative-sandbox: eventing/sources/creating-event-sources/writing-event-source/07-knative-sandbox.md
      - Sugar Controller: eventing/sugar/index.md
      - Event registry: eventing/event-registry.md
      - Event delivery: eventing/event-delivery.md
      - Debugging: eventing/debugging/README.md
      - Accessing CloudEvent traces: eventing/accessing-traces.md
      - Code samples:
        - Overview: eventing/samples/README.md
        - Container source: eventing/samples/container-source/README.md
        - Hello World:
          - Overview: eventing/samples/helloworld/README.md
          - GO: eventing/samples/helloworld/helloworld-go/README.md
          - Python: eventing/samples/helloworld/helloworld-python/README.md
        - Apache Kafka:
          - Overview: eventing/samples/kafka/README.md
          - Binding Example: eventing/samples/kafka/binding/README.md
          - Channel Example: eventing/samples/kafka/channel/README.md
          - Source Example: eventing/samples/kafka/source/README.md
        - Parallel:
          - Overview: eventing/samples/parallel/README.md
          - Multiple Cases: eventing/samples/parallel/multiple-branches/README.md
          - Mutual Exclusivity: eventing/samples/parallel/mutual-exclusivity/README.md
        - CloudAuditLogsSource: eventing/samples/cloud-audit-logs-source/README.md
        - CloudPubSubSource: eventing/samples/cloud-pubsub-source/README.md
        - CloudSchedulerSource: eventing/samples/cloud-scheduler-source/README.md
        - CloudStorageSource: eventing/samples/cloud-storage-source/README.md
        - GitHub source: eventing/samples/github-source/README.md
        - GitLab source: eventing/samples/gitlab-source/README.md
        - IoT core: eventing/samples/iot-core/README.md
    - Reference:
      - Serving: reference/api/serving.md
      - Eventing: reference/api/eventing/eventing.md
    - Client:
      - Overview: client/README.md
      - Installing kn: client/install-kn.md
      - Customizing kn: client/configure-kn.md
      - kn plugins: client/kn-plugins.md
    - "Join the Community ➠": ../community/
    - "Read the Blog ➠": ../blog/

theme:
  name: material
  logo: images/logo/rgb/knative-logo-rgb.png
  favicon: images/knative-sm.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

plugins:
  - search
  - macros:
      module_name: hack/macros
  - exclude:
      glob:
        # Exclude files that contain hugo specific shortcodes
        # (either the include shortcode or not-converted-yet tabs).
        - smoketest.md
        - "*/serving-api.md" # shortcode to serving.md
        - "*/_index.md" # pretty much all shortcodes

markdown_extensions:
  # - mdx_include:
  #     base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true


copyright: "Copyright © 2021 The Knative Authors"

extra:
  branch: v0.22.0          # Branch to use for examples
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KnativeProject
    - icon: fontawesome/brands/github
      link: https://github.com/knative/community
      name: Knative Community on Github
    - icon: fontawesome/brands/slack
      link: https://slack.knative.dev
      name: Slack
  # TODO: Replace with https://github.com/mkdocs/mkdocs/pull/2267 once mkdocs 1.2 is out.
  version_warning: !!python/object/apply:os.getenv ["VERSION_WARNING"]
  knative_version: !!python/object/apply:os.getenv ["KNATIVE_VERSION"]
  version:
    provider: mike
